// Auto-generated port of the rule table from LoopIconMatcher.swift (see
// NOTE-FOR-CLAUDE-AGENT-ICON-LABELING-BRIEF.md). Order matters: earlier,
// more specific rules win over later, broader ones.
export interface IconMatchRule {
  pattern: string;
  iconKey: string;
}

export const ICON_MATCH_RULES: IconMatchRule[] = [
  { pattern: "laundry|detergent", iconKey: "jug-detergent" },
  { pattern: "wash|dry|fold|iron|linen|linens", iconKey: "shirt" },
  { pattern: "shirt|tops|bottoms|suit|dress|clothes|clothing|wardrobe|closet|outfit", iconKey: "shirt" },
  { pattern: "shoe|shoes|sandal|boot|sneaker", iconKey: "shoe-prints" },
  { pattern: "sock|socks", iconKey: "socks" },
  { pattern: "vacuum|sweep|dust|mop", iconKey: "broom" },
  { pattern: "trash|garbage|dumpster", iconKey: "trash-can" },
  { pattern: "recycle|recycling", iconKey: "recycle" },
  { pattern: "sink|faucet|drain", iconKey: "sink" },
  { pattern: "soap", iconKey: "soap" },
  { pattern: "dish|dishes|utensil|utensils|cutlery", iconKey: "utensils" },
  { pattern: "kitchen|cook|cooking|recipe|fridge|refrigerator", iconKey: "kitchen-set" },
  { pattern: "grocery|groceries|pantry", iconKey: "basket-shopping" },
  { pattern: "coffee|mug|tea", iconKey: "mug-hot" },
  { pattern: "apple", iconKey: "apple-whole" },
  { pattern: "pizza", iconKey: "pizza-slice" },
  { pattern: "burger|meat", iconKey: "burger" },
  { pattern: "bread|toast|sandwich", iconKey: "bread-slice" },
  { pattern: "cheese", iconKey: "cheese" },
  { pattern: "egg|eggs|easter", iconKey: "egg" },
  { pattern: "wine", iconKey: "wine-glass" },
  { pattern: "beer", iconKey: "beer-mug-empty" },
  { pattern: "snack|snacks|dessert|sweet|sweets|candy|cookie|cookies", iconKey: "cookie-bite" },
  { pattern: "breakfast|lunch|dinner|meal|meals|oatmeal|eat|eating", iconKey: "bowl-food" },
  { pattern: "hang|hanging|hook|mount|nail", iconKey: "hammer" },
  { pattern: "assemble|assembly|screw|fix|repair", iconKey: "screwdriver-wrench" },
  { pattern: "paint|painting", iconKey: "paint-roller" },
  { pattern: "tool|toolbox", iconKey: "toolbox" },
  { pattern: "mirror|picture|photo|frame|poster|art", iconKey: "image" },
  { pattern: "vault|safe", iconKey: "vault" },
  { pattern: "couch|sofa", iconKey: "couch" },
  { pattern: "chair", iconKey: "chair" },
  { pattern: "bed|mattress", iconKey: "bed" },
  { pattern: "lightbulb|lamp", iconKey: "lightbulb" },
  { pattern: "plug|outlet", iconKey: "plug" },
  { pattern: "door|deadbolt", iconKey: "door-closed" },
  { pattern: "key|keys|locksmith", iconKey: "key" },
  { pattern: "shop|shopping|store|buy|purchase|order", iconKey: "cart-shopping" },
  { pattern: "gift|present", iconKey: "gift" },
  { pattern: "receipt|return", iconKey: "receipt" },
  { pattern: "mail|package|ship|deliver|delivery", iconKey: "package" },
  { pattern: "dog", iconKey: "dog" },
  { pattern: "cat|litter", iconKey: "cat" },
  { pattern: "pet|pets|vet", iconKey: "paw" },
  { pattern: "plant|plants|repot|garden|gardening", iconKey: "seedling" },
  { pattern: "compost", iconKey: "leaf" },
  { pattern: "tree|lawn|yard", iconKey: "tree" },
  { pattern: "gym|workout|exercise|lift|weights", iconKey: "dumbbell" },
  { pattern: "run|jog|running", iconKey: "person-running" },
  { pattern: "walk|walking", iconKey: "person-walking" },
  { pattern: "swim|swimming", iconKey: "person-swimming" },
  { pattern: "bike|bicycle|cycling", iconKey: "bicycle" },
  { pattern: "yoga|stretch|stretching|meditate|meditation", iconKey: "spa" },
  { pattern: "sport|sports|practice", iconKey: "basketball" },
  { pattern: "dentist|dental|tooth|teeth|floss", iconKey: "tooth" },
  { pattern: "therapy|therapist|counseling", iconKey: "comment" },
  { pattern: "med|meds|medication|pill|pills|prescription|vitamin|vitamins", iconKey: "pills" },
  { pattern: "physical therapy", iconKey: "heart-pulse" },
  { pattern: "doctor|physician|checkup|appointment", iconKey: "stethoscope" },
  { pattern: "hospital|urgent care", iconKey: "hospital" },
  { pattern: "shot|vaccine|injection|blood test", iconKey: "syringe" },
  { pattern: "bandage|first aid|wound", iconKey: "bandage" },
  { pattern: "shower|bath", iconKey: "shower" },
  { pattern: "toilet|bathroom", iconKey: "toilet" },
  { pattern: "shave|haircut|hair|nails|salon", iconKey: "scissors" },
  { pattern: "skincare", iconKey: "spa" },
  { pattern: "flight|plane|airport|fly", iconKey: "plane" },
  { pattern: "passport|visa|customs", iconKey: "passport" },
  { pattern: "hotel|airbnb|lodging|resort", iconKey: "hotel" },
  { pattern: "suitcase|pack|packing|luggage", iconKey: "suitcase" },
  { pattern: "train|subway", iconKey: "train" },
  { pattern: "bus", iconKey: "bus" },
  { pattern: "taxi|uber|lyft", iconKey: "taxi" },
  { pattern: "trip|vacation|travel|itinerary", iconKey: "map" },
  { pattern: "wedding|rsvp", iconKey: "champagne-glasses" },
  { pattern: "gas|fuel", iconKey: "gas-pump" },
  { pattern: "car|vehicle|transponder|tire|tires", iconKey: "car" },
  { pattern: "parking|dmv|license plate|registration", iconKey: "square-parking" },
  { pattern: "bill|bills|invoice|rent", iconKey: "file-invoice-dollar" },
  { pattern: "bank|deposit|budget", iconKey: "building-columns" },
  { pattern: "tax|taxes|irs", iconKey: "file-invoice" },
  { pattern: "money|expense|expenses|finance", iconKey: "wallet" },
  { pattern: "subscription|renew|renewal", iconKey: "calendar-check" },
  { pattern: "address|form|forms|paperwork|document|documents|application|license|permit", iconKey: "id-card" },
  { pattern: "call|phone|dial", iconKey: "phone" },
  { pattern: "text|message|sms", iconKey: "comment" },
  { pattern: "email|inbox", iconKey: "envelope" },
  { pattern: "meeting|zoom", iconKey: "video" },
  { pattern: "code|program|debug|develop", iconKey: "laptop-code" },
  { pattern: "computer|laptop|desktop|software", iconKey: "laptop" },
  { pattern: "wifi|router|internet|network", iconKey: "wifi" },
  { pattern: "password|login", iconKey: "lock" },
  { pattern: "backup|file|files", iconKey: "file" },
  { pattern: "charge|charging", iconKey: "charging-station" },
  { pattern: "alarm|reminder", iconKey: "bell" },
  { pattern: "book|books|read|reading|library", iconKey: "book" },
  { pattern: "class|course|study|homework|school", iconKey: "graduation-cap" },
  { pattern: "write|writing|journal|blog|note|notes", iconKey: "pen" },
  { pattern: "music|guitar|piano|instrument", iconKey: "music" },
  { pattern: "podcast|audiobook", iconKey: "podcast" },
  { pattern: "game|games|gaming|puzzle", iconKey: "gamepad" },
  { pattern: "camera", iconKey: "camera" },
  { pattern: "movie|movies|watch", iconKey: "film" },
  { pattern: "improv|acting|theater|theatre|rehearsal", iconKey: "masks-theater" },
  { pattern: "kid|kids|child|children", iconKey: "child" },
  { pattern: "baby", iconKey: "baby" },
  { pattern: "birthday|anniversary", iconKey: "cake-candles" },
  { pattern: "church|worship", iconKey: "place-of-worship" },
  { pattern: "christmas|xmas", iconKey: "sleigh" },
  { pattern: "halloween|costume|trick or treat|masquerade", iconKey: "ghost" },
  { pattern: "hanukkah|chanukah", iconKey: "hanukiah" },
  { pattern: "valentine|valentines", iconKey: "heart" },
  { pattern: "st patrick|patricks|shamrock", iconKey: "clover" },
  { pattern: "fourth of july|independence day", iconKey: "flag-usa" },
  { pattern: "new years|nye", iconKey: "champagne-glasses" },
  { pattern: "holiday|holidays", iconKey: "gift" },
  { pattern: "snow|shovel|shoveling", iconKey: "snowflake" },
  { pattern: "sunscreen", iconKey: "sun" },
  { pattern: "rain|umbrella", iconKey: "umbrella" },
  { pattern: "water|hydrate", iconKey: "droplet" },
  { pattern: "confirm|plan|plans|schedule|rsvp", iconKey: "calendar-check" },
  { pattern: "check|review|inspect", iconKey: "clipboard-check" },
  { pattern: "clean|cleaning|tidy|declutter|organize", iconKey: "broom" },
];

export const FALLBACK_ICON_KEY = "list-check";
