import type { IconType } from 'react-icons';
import {
  FaAws,
  FaBoxArchive,
  FaBridge,
  FaBug,
  FaChartLine,
  FaClock,
  FaCloud,
  FaCode,
  FaDatabase,
  FaDesktop,
  FaDocker,
  FaEnvelope,
  FaFire,
  FaFolder,
  FaGaugeHigh,
  FaGear,
  FaGithub,
  FaGlobe,
  FaGoogle,
  FaHardDrive,
  FaKey,
  FaLayerGroup,
  FaLock,
  FaMagnifyingGlass,
  FaMicrosoft,
  FaMobileScreen,
  FaNetworkWired,
  FaPlug,
  FaRoute,
  FaServer,
  FaShieldHalved,
  FaSitemap,
  FaTerminal,
  FaTriangleExclamation,
  FaUser,
  FaUsers,
  FaWindowMaximize,
  FaAppleWhole,
  FaBaby,
  FaBandage,
  FaBasketShopping,
  FaBasketball,
  FaBed,
  FaBeerMugEmpty,
  FaBell,
  FaBicycle,
  FaBook,
  FaBowlFood,
  FaBreadSlice,
  FaBroom,
  FaBuildingColumns,
  FaBurger,
  FaBus,
  FaCakeCandles,
  FaCalendarCheck,
  FaCamera,
  FaCar,
  FaCartShopping,
  FaCat,
  FaChair,
  FaChampagneGlasses,
  FaChargingStation,
  FaCheese,
  FaChild,
  FaClipboardCheck,
  FaClover,
  FaComment,
  FaCookieBite,
  FaCouch,
  FaDog,
  FaDoorClosed,
  FaDroplet,
  FaDumbbell,
  FaEgg,
  FaFile,
  FaFileInvoice,
  FaFileInvoiceDollar,
  FaFilm,
  FaFlagUsa,
  FaGamepad,
  FaGasPump,
  FaGhost,
  FaGift,
  FaGraduationCap,
  FaHammer,
  FaHanukiah,
  FaHeart,
  FaHeartPulse,
  FaHospital,
  FaHotel,
  FaIdCard,
  FaImage,
  FaJugDetergent,
  FaKitchenSet,
  FaLaptop,
  FaLaptopCode,
  FaLeaf,
  FaLightbulb,
  FaMap,
  FaMasksTheater,
  FaMugHot,
  FaMusic,
  FaPaintRoller,
  FaPassport,
  FaPaw,
  FaPen,
  FaPersonRunning,
  FaPersonSwimming,
  FaPersonWalking,
  FaPhone,
  FaPills,
  FaPizzaSlice,
  FaPlaceOfWorship,
  FaPlane,
  FaPodcast,
  FaReceipt,
  FaRecycle,
  FaScissors,
  FaScrewdriverWrench,
  FaSeedling,
  FaShirt,
  FaShoePrints,
  FaShower,
  FaSink,
  FaSleigh,
  FaSnowflake,
  FaSoap,
  FaSocks,
  FaSpa,
  FaSquareParking,
  FaStethoscope,
  FaSuitcase,
  FaSun,
  FaSyringe,
  FaTaxi,
  FaToilet,
  FaToolbox,
  FaListCheck,
  FaTooth,
  FaTrain,
  FaTrashCan,
  FaTree,
  FaUmbrella,
  FaUtensils,
  FaVault,
  FaVideo,
  FaWallet,
  FaWifi,
  FaWineGlass,
  FaBucket,
  FaWarehouse,
  FaCube,
  FaCertificate,
  FaWrench,
  FaBoxesStacked,
  FaShuffle,
  FaList,
  FaDiagramProject,
  FaCircleNodes,
  FaHexagonNodes,
} from 'react-icons/fa6';

/**
 * The icon library available to nodes: a curated infra/cloud set plus a
 * large port of the keyword-matching vocabulary from LoopIconMatcher.swift
 * (see NOTE-FOR-CLAUDE-AGENT-ICON-LABELING-BRIEF.md) so automatic labeling
 * (src/icons/iconMatcher.ts) and manual picking draw from the same pool.
 * All Font Awesome 6 Solid via react-icons so everything renders at one
 * visual weight. No dedicated AWS *service* icon set here - Simple Icons
 * dropped Amazon's marks and AWS does not publish an official npm package
 * for its architecture icons - so cloud-platform coverage is brand logos
 * only (aws/google/microsoft/docker/github).
 */
export interface IconOption {
  key: string;
  label: string;
  Icon: IconType;
}

export const ICON_OPTIONS: IconOption[] = [
  { key: "server", label: "Server", Icon: FaServer },
  { key: "database", label: "Database", Icon: FaDatabase },
  { key: "hard-drive", label: "Storage", Icon: FaHardDrive },
  { key: "cloud", label: "Cloud", Icon: FaCloud },
  { key: "globe", label: "Globe / Internet", Icon: FaGlobe },
  { key: "network", label: "Network", Icon: FaNetworkWired },
  { key: "route", label: "Router / DNS", Icon: FaRoute },
  { key: "gauge", label: "Load balancer", Icon: FaGaugeHigh },
  { key: "bridge", label: "Gateway", Icon: FaBridge },
  { key: "plug", label: "API", Icon: FaPlug },
  { key: "envelope", label: "Queue / Messaging", Icon: FaEnvelope },
  { key: "layer-group", label: "Cluster / Group", Icon: FaLayerGroup },
  { key: "sitemap", label: "Subsystem", Icon: FaSitemap },
  { key: "box", label: "Container", Icon: FaBoxArchive },
  { key: "folder", label: "Storage bucket", Icon: FaFolder },
  { key: "terminal", label: "Compute / CLI", Icon: FaTerminal },
  { key: "code", label: "Function / Lambda", Icon: FaCode },
  { key: "gear", label: "Service", Icon: FaGear },
  { key: "lock", label: "Encryption", Icon: FaLock },
  { key: "key", label: "Auth / Keys", Icon: FaKey },
  { key: "shield", label: "Firewall / Security", Icon: FaShieldHalved },
  { key: "user", label: "User / Actor", Icon: FaUser },
  { key: "users", label: "Users", Icon: FaUsers },
  { key: "browser", label: "Browser / Client", Icon: FaWindowMaximize },
  { key: "desktop", label: "Desktop app", Icon: FaDesktop },
  { key: "mobile", label: "Mobile app", Icon: FaMobileScreen },
  { key: "chart", label: "Analytics", Icon: FaChartLine },
  { key: "search", label: "Search", Icon: FaMagnifyingGlass },
  { key: "clock", label: "Scheduler / Cron", Icon: FaClock },
  { key: "fire", label: "Cache", Icon: FaFire },
  { key: "bug", label: "Monitoring / Errors", Icon: FaBug },
  { key: "alert", label: "Alert", Icon: FaTriangleExclamation },
  { key: "aws", label: "AWS", Icon: FaAws },
  { key: "google", label: "Google Cloud", Icon: FaGoogle },
  { key: "microsoft", label: "Azure / Microsoft", Icon: FaMicrosoft },
  { key: "docker", label: "Docker", Icon: FaDocker },
  { key: "github", label: "GitHub", Icon: FaGithub },
{ key: "apple-whole", label: "Apple Whole", Icon: FaAppleWhole },
  { key: "baby", label: "Baby", Icon: FaBaby },
  { key: "bandage", label: "Bandage", Icon: FaBandage },
  { key: "basket-shopping", label: "Basket Shopping", Icon: FaBasketShopping },
  { key: "basketball", label: "Basketball", Icon: FaBasketball },
  { key: "bed", label: "Bed", Icon: FaBed },
  { key: "beer-mug-empty", label: "Beer Mug Empty", Icon: FaBeerMugEmpty },
  { key: "bell", label: "Bell", Icon: FaBell },
  { key: "bicycle", label: "Bicycle", Icon: FaBicycle },
  { key: "book", label: "Book", Icon: FaBook },
  { key: "bowl-food", label: "Bowl Food", Icon: FaBowlFood },
  { key: "bread-slice", label: "Bread Slice", Icon: FaBreadSlice },
  { key: "broom", label: "Broom", Icon: FaBroom },
  { key: "building-columns", label: "Building Columns", Icon: FaBuildingColumns },
  { key: "burger", label: "Burger", Icon: FaBurger },
  { key: "bus", label: "Bus", Icon: FaBus },
  { key: "cake-candles", label: "Cake Candles", Icon: FaCakeCandles },
  { key: "calendar-check", label: "Calendar Check", Icon: FaCalendarCheck },
  { key: "camera", label: "Camera", Icon: FaCamera },
  { key: "car", label: "Car", Icon: FaCar },
  { key: "cart-shopping", label: "Cart Shopping", Icon: FaCartShopping },
  { key: "cat", label: "Cat", Icon: FaCat },
  { key: "chair", label: "Chair", Icon: FaChair },
  { key: "champagne-glasses", label: "Champagne Glasses", Icon: FaChampagneGlasses },
  { key: "charging-station", label: "Charging Station", Icon: FaChargingStation },
  { key: "cheese", label: "Cheese", Icon: FaCheese },
  { key: "child", label: "Child", Icon: FaChild },
  { key: "clipboard-check", label: "Clipboard Check", Icon: FaClipboardCheck },
  { key: "clover", label: "Clover", Icon: FaClover },
  { key: "comment", label: "Comment", Icon: FaComment },
  { key: "cookie-bite", label: "Cookie Bite", Icon: FaCookieBite },
  { key: "couch", label: "Couch", Icon: FaCouch },
  { key: "dog", label: "Dog", Icon: FaDog },
  { key: "door-closed", label: "Door Closed", Icon: FaDoorClosed },
  { key: "droplet", label: "Droplet", Icon: FaDroplet },
  { key: "dumbbell", label: "Dumbbell", Icon: FaDumbbell },
  { key: "egg", label: "Egg", Icon: FaEgg },
  { key: "file", label: "File", Icon: FaFile },
  { key: "file-invoice", label: "File Invoice", Icon: FaFileInvoice },
  { key: "file-invoice-dollar", label: "File Invoice Dollar", Icon: FaFileInvoiceDollar },
  { key: "film", label: "Film", Icon: FaFilm },
  { key: "flag-usa", label: "Flag Usa", Icon: FaFlagUsa },
  { key: "gamepad", label: "Gamepad", Icon: FaGamepad },
  { key: "gas-pump", label: "Gas Pump", Icon: FaGasPump },
  { key: "ghost", label: "Ghost", Icon: FaGhost },
  { key: "gift", label: "Gift", Icon: FaGift },
  { key: "graduation-cap", label: "Graduation Cap", Icon: FaGraduationCap },
  { key: "hammer", label: "Hammer", Icon: FaHammer },
  { key: "hanukiah", label: "Hanukiah", Icon: FaHanukiah },
  { key: "heart", label: "Heart", Icon: FaHeart },
  { key: "heart-pulse", label: "Heart Pulse", Icon: FaHeartPulse },
  { key: "hospital", label: "Hospital", Icon: FaHospital },
  { key: "hotel", label: "Hotel", Icon: FaHotel },
  { key: "id-card", label: "Id Card", Icon: FaIdCard },
  { key: "image", label: "Image", Icon: FaImage },
  { key: "jug-detergent", label: "Jug Detergent", Icon: FaJugDetergent },
  { key: "kitchen-set", label: "Kitchen Set", Icon: FaKitchenSet },
  { key: "laptop", label: "Laptop", Icon: FaLaptop },
  { key: "laptop-code", label: "Laptop Code", Icon: FaLaptopCode },
  { key: "leaf", label: "Leaf", Icon: FaLeaf },
  { key: "list-check", label: "List Check", Icon: FaListCheck },
  { key: "lightbulb", label: "Lightbulb", Icon: FaLightbulb },
  { key: "map", label: "Map", Icon: FaMap },
  { key: "masks-theater", label: "Masks Theater", Icon: FaMasksTheater },
  { key: "mug-hot", label: "Mug Hot", Icon: FaMugHot },
  { key: "music", label: "Music", Icon: FaMusic },
  { key: "paint-roller", label: "Paint Roller", Icon: FaPaintRoller },
  { key: "passport", label: "Passport", Icon: FaPassport },
  { key: "paw", label: "Paw", Icon: FaPaw },
  { key: "pen", label: "Pen", Icon: FaPen },
  { key: "person-running", label: "Person Running", Icon: FaPersonRunning },
  { key: "person-swimming", label: "Person Swimming", Icon: FaPersonSwimming },
  { key: "person-walking", label: "Person Walking", Icon: FaPersonWalking },
  { key: "phone", label: "Phone", Icon: FaPhone },
  { key: "pills", label: "Pills", Icon: FaPills },
  { key: "pizza-slice", label: "Pizza Slice", Icon: FaPizzaSlice },
  { key: "place-of-worship", label: "Place Of Worship", Icon: FaPlaceOfWorship },
  { key: "plane", label: "Plane", Icon: FaPlane },
  { key: "podcast", label: "Podcast", Icon: FaPodcast },
  { key: "receipt", label: "Receipt", Icon: FaReceipt },
  { key: "recycle", label: "Recycle", Icon: FaRecycle },
  { key: "scissors", label: "Scissors", Icon: FaScissors },
  { key: "screwdriver-wrench", label: "Screwdriver Wrench", Icon: FaScrewdriverWrench },
  { key: "seedling", label: "Seedling", Icon: FaSeedling },
  { key: "shirt", label: "Shirt", Icon: FaShirt },
  { key: "shoe-prints", label: "Shoe Prints", Icon: FaShoePrints },
  { key: "shower", label: "Shower", Icon: FaShower },
  { key: "sink", label: "Sink", Icon: FaSink },
  { key: "sleigh", label: "Sleigh", Icon: FaSleigh },
  { key: "snowflake", label: "Snowflake", Icon: FaSnowflake },
  { key: "soap", label: "Soap", Icon: FaSoap },
  { key: "socks", label: "Socks", Icon: FaSocks },
  { key: "spa", label: "Spa", Icon: FaSpa },
  { key: "square-parking", label: "Square Parking", Icon: FaSquareParking },
  { key: "stethoscope", label: "Stethoscope", Icon: FaStethoscope },
  { key: "suitcase", label: "Suitcase", Icon: FaSuitcase },
  { key: "sun", label: "Sun", Icon: FaSun },
  { key: "syringe", label: "Syringe", Icon: FaSyringe },
  { key: "taxi", label: "Taxi", Icon: FaTaxi },
  { key: "toilet", label: "Toilet", Icon: FaToilet },
  { key: "toolbox", label: "Toolbox", Icon: FaToolbox },
  { key: "tooth", label: "Tooth", Icon: FaTooth },
  { key: "train", label: "Train", Icon: FaTrain },
  { key: "trash-can", label: "Trash Can", Icon: FaTrashCan },
  { key: "tree", label: "Tree", Icon: FaTree },
  { key: "umbrella", label: "Umbrella", Icon: FaUmbrella },
  { key: "utensils", label: "Utensils", Icon: FaUtensils },
  { key: "vault", label: "Vault", Icon: FaVault },
  { key: "video", label: "Video", Icon: FaVideo },
  { key: "wallet", label: "Wallet", Icon: FaWallet },
  { key: "wifi", label: "Wifi", Icon: FaWifi },
  { key: "wine-glass", label: "Wine Glass", Icon: FaWineGlass },
  { key: "bucket", label: "Bucket (S3)", Icon: FaBucket },
  { key: "warehouse", label: "Warehouse", Icon: FaWarehouse },
  { key: "cube", label: "Cube / Module", Icon: FaCube },
  { key: "certificate", label: "Certificate", Icon: FaCertificate },
  { key: "wrench", label: "Maintenance / Ops", Icon: FaWrench },
  { key: "boxes-stacked", label: "Bulk Storage", Icon: FaBoxesStacked },
  { key: "shuffle", label: "Routing / Balancing", Icon: FaShuffle },
  { key: "list", label: "Queue / List", Icon: FaList },
  { key: "diagram-project", label: "Architecture Diagram", Icon: FaDiagramProject },
  { key: "circle-nodes", label: "Network / Cluster", Icon: FaCircleNodes },
  { key: "hexagon-nodes", label: "Distributed Nodes", Icon: FaHexagonNodes },
];

const ICON_BY_KEY = new Map(ICON_OPTIONS.map((opt) => [opt.key, opt.Icon]));

export function getIconComponent(key: string | undefined): IconType | undefined {
  if (!key) return undefined;
  return ICON_BY_KEY.get(key);
}
