import type { IconType } from 'react-icons';
import {
  FaAws,
  FaBridge,
  FaBug,
  FaChartLine,
  FaClock,
  FaCloud,
  FaCode,
  FaDatabase,
  FaDesktop,
  FaDocker,
  FaEnvelope,
  FaFire,
  FaFolder,
  FaGaugeHigh,
  FaGear,
  FaGithub,
  FaGlobe,
  FaGoogle,
  FaHardDrive,
  FaKey,
  FaLayerGroup,
  FaLock,
  FaMagnifyingGlass,
  FaMicrosoft,
  FaMobileScreen,
  FaNetworkWired,
  FaPlug,
  FaRoute,
  FaServer,
  FaShieldHalved,
  FaSitemap,
  FaTerminal,
  FaTriangleExclamation,
  FaUser,
  FaUsers,
  FaWindowMaximize,
  FaFile,
  FaFileInvoice,
  FaFileInvoiceDollar,
  FaLaptop,
  FaLaptopCode,
  FaImage,
  FaVideo,
  FaComment,
  FaIdCard,
  FaReceipt,
  FaPhone,
  FaCalendarCheck,
  FaTrashCan,
  FaVault,
  FaBell,
  FaClipboardCheck,
  FaMap,
  FaListCheck,
  FaBucket,
  FaWarehouse,
  FaCube,
  FaCertificate,
  FaWrench,
  FaBoxesStacked,
  FaShuffle,
  FaList,
  FaDiagramProject,
  FaCircleNodes,
  FaHexagonNodes,
  FaArrowRightLong,
  FaMinus,
  FaCopy,
  FaPaste,
  FaDownload,
  FaUpload,
  FaArrowsRotate,
  FaFilter,
  FaBan,
  FaCircleCheck,
  FaCircleXmark,
  FaFlask,
  FaSignal,
  FaRocket,
  FaTable,
  FaFileZipper,
  FaCubes,
  FaShieldVirus,
  FaCodeCompare,
  FaCodeBranch,
  FaCodeMerge,
  FaCodePullRequest,
  FaBox,
} from 'react-icons/fa6';

/**
 * The icon library available to nodes: a curated set for architecture/data/
 * infra diagramming (compute, storage, networking, messaging, security,
 * clients, observability, CI/CD, source control) plus a handful of general
 * business/document icons (file, invoice, id card...) that show up in
 * non-infra diagrams too. All Font Awesome 6 Solid via react-icons so
 * everything renders at one visual weight. No dedicated AWS *service* icon
 * set here - Simple Icons dropped Amazon's marks and AWS does not publish
 * an official npm package for its architecture icons - so cloud-platform
 * coverage is brand logos only (aws/google/microsoft/docker/github).
 */
export interface IconOption {
  key: string;
  label: string;
  Icon: IconType;
}

export const ICON_OPTIONS: IconOption[] = [
  { key: "server", label: "Server", Icon: FaServer },
  { key: "database", label: "Database", Icon: FaDatabase },
  { key: "table", label: "Table", Icon: FaTable },
  { key: "hard-drive", label: "Storage", Icon: FaHardDrive },
  { key: "cloud", label: "Cloud", Icon: FaCloud },
  { key: "globe", label: "Globe / Internet", Icon: FaGlobe },
  { key: "network", label: "Network", Icon: FaNetworkWired },
  { key: "route", label: "Router / DNS", Icon: FaRoute },
  { key: "gauge", label: "Load balancer", Icon: FaGaugeHigh },
  { key: "bridge", label: "Gateway", Icon: FaBridge },
  { key: "plug", label: "API", Icon: FaPlug },
  { key: "signal", label: "Signal / Status", Icon: FaSignal },
  { key: "envelope", label: "Queue / Messaging", Icon: FaEnvelope },
  { key: "layer-group", label: "Cluster / Group", Icon: FaLayerGroup },
  { key: "sitemap", label: "Subsystem", Icon: FaSitemap },
  { key: "cubes", label: "Microservices", Icon: FaCubes },
  { key: "folder", label: "Storage bucket", Icon: FaFolder },
  { key: "terminal", label: "Compute / CLI", Icon: FaTerminal },
  { key: "code", label: "Function / Lambda", Icon: FaCode },
  { key: "gear", label: "Service", Icon: FaGear },
  { key: "rocket", label: "Deploy / Launch", Icon: FaRocket },
  { key: "flask", label: "Test / Staging", Icon: FaFlask },
  { key: "lock", label: "Encryption", Icon: FaLock },
  { key: "key", label: "Auth / Keys", Icon: FaKey },
  { key: "shield", label: "Firewall / Security", Icon: FaShieldHalved },
  { key: "shield-virus", label: "Malware / AV Scan", Icon: FaShieldVirus },
  { key: "user", label: "User / Actor", Icon: FaUser },
  { key: "users", label: "Users", Icon: FaUsers },
  { key: "browser", label: "Browser / Client", Icon: FaWindowMaximize },
  { key: "desktop", label: "Desktop app", Icon: FaDesktop },
  { key: "mobile", label: "Mobile app", Icon: FaMobileScreen },
  { key: "laptop", label: "Laptop", Icon: FaLaptop },
  { key: "laptop-code", label: "Dev Machine", Icon: FaLaptopCode },
  { key: "chart", label: "Analytics", Icon: FaChartLine },
  { key: "search", label: "Search", Icon: FaMagnifyingGlass },
  { key: "filter", label: "Filter", Icon: FaFilter },
  { key: "clock", label: "Scheduler / Cron", Icon: FaClock },
  { key: "fire", label: "Cache", Icon: FaFire },
  { key: "bug", label: "Monitoring / Errors", Icon: FaBug },
  { key: "alert", label: "Alert", Icon: FaTriangleExclamation },
  { key: "bell", label: "Notification", Icon: FaBell },
  { key: "circle-check", label: "Pass / Success", Icon: FaCircleCheck },
  { key: "circle-xmark", label: "Fail / Error", Icon: FaCircleXmark },
  { key: "ban", label: "Blocked / Quarantine", Icon: FaBan },
  { key: "clipboard-check", label: "Audit / Checklist", Icon: FaClipboardCheck },
  { key: "aws", label: "AWS", Icon: FaAws },
  { key: "google", label: "Google Cloud", Icon: FaGoogle },
  { key: "microsoft", label: "Azure / Microsoft", Icon: FaMicrosoft },
  { key: "docker", label: "Docker", Icon: FaDocker },
  { key: "github", label: "GitHub", Icon: FaGithub },
  { key: "code-branch", label: "Branch", Icon: FaCodeBranch },
  { key: "code-merge", label: "Merge", Icon: FaCodeMerge },
  { key: "code-compare", label: "Diff / Compare", Icon: FaCodeCompare },
  { key: "pull-request", label: "Pull Request", Icon: FaCodePullRequest },
  { key: "package", label: "Package / Artifact", Icon: FaBox },
  { key: "copy", label: "Copy", Icon: FaCopy },
  { key: "paste", label: "Paste", Icon: FaPaste },
  { key: "download", label: "Download", Icon: FaDownload },
  { key: "upload", label: "Upload", Icon: FaUpload },
  { key: "sync", label: "Sync / Refresh", Icon: FaArrowsRotate },
  { key: "archive-zip", label: "Archive / Compress", Icon: FaFileZipper },
  { key: "trash-can", label: "Delete", Icon: FaTrashCan },
  { key: "vault", label: "Vault / Secrets", Icon: FaVault },
  { key: "file", label: "File", Icon: FaFile },
  { key: "file-invoice", label: "Invoice", Icon: FaFileInvoice },
  { key: "file-invoice-dollar", label: "Billing", Icon: FaFileInvoiceDollar },
  { key: "image", label: "Image", Icon: FaImage },
  { key: "video", label: "Video", Icon: FaVideo },
  { key: "comment", label: "Comment / Message", Icon: FaComment },
  { key: "id-card", label: "Identity", Icon: FaIdCard },
  { key: "receipt", label: "Receipt", Icon: FaReceipt },
  { key: "phone", label: "Phone", Icon: FaPhone },
  { key: "calendar-check", label: "Schedule", Icon: FaCalendarCheck },
  { key: "map", label: "Map / Geo", Icon: FaMap },
  { key: "list-check", label: "List Check", Icon: FaListCheck },
  { key: "bucket", label: "Bucket (S3)", Icon: FaBucket },
  { key: "warehouse", label: "Warehouse", Icon: FaWarehouse },
  { key: "cube", label: "Cube / Module", Icon: FaCube },
  { key: "certificate", label: "Certificate", Icon: FaCertificate },
  { key: "wrench", label: "Maintenance / Ops", Icon: FaWrench },
  { key: "boxes-stacked", label: "Bulk Storage", Icon: FaBoxesStacked },
  { key: "shuffle", label: "Routing / Balancing", Icon: FaShuffle },
  { key: "list", label: "Queue / List", Icon: FaList },
  { key: "diagram-project", label: "Architecture Diagram", Icon: FaDiagramProject },
  { key: "circle-nodes", label: "Network / Cluster", Icon: FaCircleNodes },
  { key: "hexagon-nodes", label: "Distributed Nodes", Icon: FaHexagonNodes },
  { key: "arrow", label: "Arrow / Flow", Icon: FaArrowRightLong },
  { key: "line", label: "Line / Connector", Icon: FaMinus },
];

const ICON_BY_KEY = new Map(ICON_OPTIONS.map((opt) => [opt.key, opt.Icon]));

export function getIconComponent(key: string | undefined): IconType | undefined {
  if (!key) return undefined;
  return ICON_BY_KEY.get(key);
}
